### ISSUE TITLE
Installation and use on a Cray HPC cluster

### ISSUE THREAD

**Issue by menzzana** [snoweye/pbdMPI#46]
I tried to install the library on a Cray HPC cluster using...

`install.packages("pbdMPI", configure.args="--with-mpi-type=MPICH --with-mpi-include=/opt/cray/pe/mpich/8.1.25/ofi/crayclang/10.0/include --with-mpi-libpath=/opt/cray/pe/mpich/8.1.25/ofi/crayclang/10.0/lib --with-mpi=/opt/cray/pe/mpich/8.1.25/ofi/crayclang/10.0")`

The installation does not complain but running the code demo.R
complains about *No MPI executable can be found.*

I guess it is related to that on cray we use *srun* to start the job instead of *mpirun*

Any suggestions on how to install and use this library on a Cray machine?

**Comment by snoweye** [comment]
This does not seem to be problems of the package nor R. If interactive is needed, then mpi commends need to be available (e.g., in path environment). If batch is allowed, then similar solutions may be found at [python and mpi](https://github.com/akkornel/mpi4py?tab=readme-ov-file#synchronous-slurm-with-salloc) or [via sbatch](https://github.com/akkornel/mpi4py?tab=readme-ov-file#slurm-batch-jobs-with-sbatch).
